<?php
	require('app\templates\inc\header.phtml');
?>

<div class="container">
	<form action="" class="login-form w-100 w-md-50 w-lg-25" method="POST">
		<legend> Sign Up to Our Platform</legend>
		<div class="form-group mb-3">
			<input placeholder="Username" name="username" type="text" class="form-control form-control-md <?= isset($this->errors['username']) ? 'is-invalid' : '' ?>">
			<?php if(isset($this->errors['username'])): ?>
				<div class="invalid-feedback">
					<?=$this->errors['username']?>
				</div>
			<?php endif;?>
		</div>
		<div class="form-group mb-3">
			<input placeholder="Email Address" type="email" name="email" class="form-control form-control-md <?= isset($this->errors['email']) ? 'is-invalid' : '' ?>">
			<?php if(isset($this->errors['email'])): ?>
				<div class="invalid-feedback">
					<?=$this->errors['email']?>
				</div>
			<?php endif;?>
		</div>
		<div class="form-group mb-3">
			<input placeholder="Password" type="password" name="password" class="form-control form-control-md <?= isset($this->errors['password']) ? 'is-invalid' : '' ?>">
			<?php if(isset($this->errors['password'])): ?>
				<div class="invalid-feedback">
					<?=$this->errors['password']?>
				</div>
			<?php endif;?>
		</div>
		<div class="form-group mb-3">
			<input placeholder="Confirm Password" type="password" name="confirm_password" class="form-control form-control-md <?= isset($this->errors['confirm_password']) ? 'is-invalid' : '' ?>">
			<?php if(isset($this->errors['confirm_password'])): ?>
				<div class="invalid-feedback">
					<?=$this->errors['confirm_password']?>
				</div>
			<?php endif;?>
		</div>
		<div class="form-group">
			<button class="btn btn-square btn-primary w-100" type="submit">Sign Up</button>
		</div>
		<div class="form-group mt-2">
			<div class="row align-items-center">
				
				<div class="col-6">
					Already have account?
				</div>
				<div class="col-6">
					<a href="<?php echo $this->route->url_for('auth_login'); ?>" class="btn btn-link">Sign In</a>
				</div>
			</div>
		</div>
	</form>
</div>