<ul class="nav navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="<?=$this->route->url_for('admin_entry')?>">
           <i class="bi bi-files"></i> Entries
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?=$this->route->url_for('admin_user')?>">
            <i class="bi bi-people"></i> Users
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?=$this->route->url_for('admin_comment')?>">
            <i class="bi bi-chat-dots"></i> Comments
        </a>
    </li>
</ul>