<?php
	require('app\templates\inc\header.phtml');
?>
<?php require('app\templates\admin\inc\navbar.phtml');?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-sm-12">
				<?php require(str_replace("\\",sp, 'app\\templates\\admin\\inc\\sidebar.phtml'));?>
			</div>
			<div class="col-md-10 col-sm-12">
				<div class="row mt-2">
					<div class="col-md-2">
						<select name="" id="" class=" dropdown select-menu">
							<option value="" selected disabled>Select Action</option>
							<option value="">Delete</option>
							<option value="">Publish</option>
							<option value="">Unpublish</option>
						</select>
					</div>
					<div class="col-md-6">
						<form action="<?=$this->route->url_for('admin_comment')?>" method="get">
							<input type="search" name="query" id="search" placeholder="Search comments" class="form-control">
						</form>
					</div>
					<div class="col-md-4">
						<a href="<?=$this->route->url_for('admin_comment_create')?>" class="btn btn-primary"> <i class="bi bi-plus"></i> Create Comment</a>
					</div>
				</div>
				<?php if($this->comments() != null): ?>
				<div class="table-responsive mt-3">
					<table class="table table-striped">
						<thead class="bg-primary text-white">
							<th>
								<input type="checkbox" class="select_all checkbox">
							</th>
							<th>Content</th>
							<th>Status</th>
							<th>Created</th>
							<th>Actions</th>
						</thead>
						<tbody>
							<?php
								foreach($this->comments() as $comment): 
							?>
							    <tr>
							    	<td>
							    		<input type="checkbox" class="checkbox item" value="<?=$comment->id?>">
							    	</td>
							    	<td>
							    		<a class="text-decoration-none" href="<?=$this->route->url_for("admin_comment_edit", ['id'=>$comment->id])?>"><?=$comment->content?></a>
							    	</td>
							    	<td>
							    		<a href="<?=$this->route->url_for("admin_comment_publish", ['id'=>$comment->id])?>">
										<i class="bi bi-<?=($comment->is_published == 1) ? 'check-circle text-success' : 'x-circle text-danger'?>"></i>
									</a>
							    	</td>
							    	<td>
							    		<?=date_format(new DateTime($comment->date_created), "F j, Y")?>
							    	</td>
									<td>
										<a class="btn-delete" href="<?=$this->route->url_for("admin_comment_delete", ['id'=>$comment->id])?>">
											<i class="bi bi-trash"></i>
										</a>
									</td>
							    </tr>

						    <?php 
								endforeach;
							?>
						</tbody>
					</table>
				</div>
				<?php else: ?>
					<div class="alert alert-info mt-2">
						No Comments found
					</div>
				<?php endif; ?>
			</div>
		</div><!-- row -->
	</div><!-- container-fluid -->
<?php require('app\templates\inc\footer.phtml');?>