<?php
	require('app\templates\inc\header.phtml');
?>
<?php require('app\templates\admin\inc\navbar.phtml');?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-sm-12">
				<?php require(str_replace("\\",sp, 'app\\templates\\admin\\inc\\sidebar.phtml'));?>
			</div>
			<div class="col-md-10 col-sm-12">
				<h1 class="page-heading text-success"><?=isset($this->comment)? 'Edit' : 'Add'?> Comment</h1>
				<form action="<?=$this->route->url_for('admin_comment_create')?>" method="post">
					<div class="form-group">
						<label for="content">Content</label>
						<textarea class="form-control" id="content" name="content">
							<?=isset($this->comment)? $this->comment->content:'';?>
						</textarea>
					</div>
                    <div class="form-group">
                        <label for="post_id">Post</label>
                        <select class="form-control" id="post_id" name="post_id">
                            <?php foreach($this->posts() as $post):?>
                                <option value="<?=$post->id?>" ><?=$post->title?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
					<div class="form-group">
						<label for="is_published">Is Published</label>
						<input type="checkbox" class="checkbox is_published" name="is_published" <?=isset($this->comment)? $this->comment->is_published == 1 ? 'checked' : '':'';?>>
					</div>
					<div class="form-group">
							<button type="submit" class="btn btn-primary">Save </button>
							<button type="reset" class="btn btn-danger">Save & Continue </button>
							<button type="button" class="btn btn-secondary">Cancel</button>
						</div>
					</div>
				</form>
			</div>
		</div><!-- row -->
	</div><!-- container-fluid -->