<?php
	require('app\templates\inc\header.phtml');
	
?>
<?php require('app\templates\admin\inc\navbar.phtml');?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-sm-12">
				<?php require(str_replace("\\",sp, 'app\\templates\\admin\\inc\\sidebar.phtml'));?>
			</div>
			<div class="col-md-10 col-sm-12">
				<h1 class="page-heading text-success">Pfura Rural District Council Administration</h1>
				<div class="row stat-section">
					<div class="col-md-3 col-sm-12">
						<div class="admin-card">
							<div class="admin-card-icon">
								<i class="bi bi-people"></i>
							</div>
							<div class="admin-card-content">
								<div class="admin-card-header">Users</div>
								<div class="admin-card-body">
									<?=$this->usersCount();?>
								</div>
								<div class="admin-card-footer">
									
								</div>
							</div><!-- card -->
						</div><!--admin-card-->
					</div>
					<div class="col-md-3 col-sm-12">
						<div class="admin-card">
							<div class="admin-card-icon">
								<i class="bi bi-files"></i>
							</div>
							
							<div class="admin-card-content">
								<div class="admin-card-header">Entries</div>
								<div class="admin-card-body">
									<?=$this->entriesCount();?>
								</div>
								<div class="admin-card-footer">
								</div>
							</div>
						</div><!-- card -->
					</div>
					<div class="col-md-3 col-sm-12">
						<div class="card">
							<div class="card-header">Users</div>
							<div class="card-body">
								
							</div>
							<div class="card-footer">
								
							</div>
						</div><!-- card -->
					</div>
					<div class="col-md-3 col-sm-12">
						<div class="card">
							<div class="card-header">Users</div>
							<div class="card-body">
								
							</div>
							<div class="card-footer">
								
							</div>
						</div><!-- card -->
					</div>
				</div>
			</div>
		</div><!-- row -->
	</div><!-- container-fluid -->