<?php
	require('app\templates\inc\header.phtml');
?>
<?php require('app\templates\admin\inc\navbar.phtml');?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-sm-12">
				<?php require(str_replace("\\",sp, 'app\\templates\\admin\\inc\\sidebar.phtml'));?>
			</div>
			<div class="col-md-10 col-sm-12">
				<div class="row mt-2">
					<div class="col-md-2">
						<select class="select-menu">
							<option value="">Select Action</option>
							<option value="delete">Delete</option>
						</select>
					</div>
					<div class="col-md-6">
						<form >
							<input type="text" class="form-control" placeholder="Search">
						</form>
					</div>
					<div class="col-md-4">
						<a href="<?=$this->route->url_for('admin_user_create')?>" class="btn btn-primary">
							<i class="bi bi-person-plus"></i> Add User</a>
					</div>
				</div>
				<?php if($this->users()): ?>
					<div class="table-responsive mt-2">
						<table class="table table-striped">
							<thead class="bg-primary text-white">
								<th>
									<input type="checkbox" class="checkbox">
								</th>
								<th>Username</th>
								<th>Email</th>
								<th>Status</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php foreach($this->users() as $user): ?>
									<tr>
										<td>
											<input type="checkbox" class="checkbox">
										</td>
										<td>
											<a href="<?=$this->route->url_for("admin_user_edit", ['id'=>$user->id])?>">
												<?=$user->username?>
								            </a>
										</td>
										<td>
											<?=$user->email?>
										</td>
										<td>
											<a href="<?=$this->route->url_for('admin_user_publish', ['id'=>$user->id])?>">
												<i class="bi bi-<?=($user->is_active == 1) ? 'check-circle' : 'x-circle'?>"></i>
											</a>
										</td>
										<td>
											<a href="<?=$this->route->url_for('admin_user_delete', ['id'=>$user->id])?>">
												<i class="bi bi-trash"></i>
											</a>
										</td>
									</tr>

								<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				<?php else: ?>
				<div class="mt-2 alert alert-info">
					No users found
				</div>
				<?php endif; ?>
			</div>
		</div><!-- row -->
	</div><!-- container-fluid -->